# Generated by Django 3.2.7 on 2021-09-04 06:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='blog_icon/')),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, verbose_name='記事の説明')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開ステータス')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
