# Generated by Django 3.2.7 on 2021-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210904_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_public',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='blog',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='blog_icon/', verbose_name='main_image'),
        ),
    ]
